version: '3.8'
services: 
    api:
      container_name: pcibex-to-postgres
      build: .
      env_file: .env 
      ports: 
        - 3000:3000
      environment: 
        - $CONNECTION_STRING
        - $POSTGRES_TABLE
        - $COLNAME_ID 
        - $COLNAME_DATA
        - $TRUSTED_ORIGIN
        - $REQUIRED_URLVARS
networks:
  default:
    external:
      name: exbuilder_deployer